// GENERATED by tools/gen_pricing.py from pipeline/pricing.py.
// Do not edit: run the generator instead. The three platforms
// drifted apart when this was hand-maintained.

export const PRICING = {
  "version": 1,
  "learn": [
    {
      "key": "free",
      "name": "Free",
      "book": "learn",
      "eurMonth": 0,
      "eurYear": 0,
      "inrMonth": 0,
      "inrYear": 0,
      "generations": null,
      "blurb": "Unlimited watching of the public library.",
      "features": [
        "Unlimited watching",
        "Quiz tracking",
        "Concept map",
        "7 caption languages"
      ],
      "seatMin": 1,
      "contactOnly": false
    },
    {
      "key": "pro",
      "name": "Pro",
      "book": "learn",
      "eurMonth": 12,
      "eurYear": 99,
      "inrMonth": 499,
      "inrYear": 4990,
      "generations": null,
      "blurb": "For an engineer learning on their own time.",
      "features": [
        "Everything in Free",
        "Runnable notebooks",
        "Structured paths",
        "Certificates",
        "Offline downloads",
        "No ads"
      ],
      "seatMin": 1,
      "contactOnly": false
    },
    {
      "key": "team",
      "name": "Team",
      "book": "learn",
      "eurMonth": 18,
      "eurYear": null,
      "inrMonth": 1500,
      "inrYear": null,
      "generations": null,
      "blurb": "For a company training its engineers.",
      "features": [
        "Everything in Pro",
        "SSO",
        "SCORM export",
        "LTI 1.3 launch",
        "Admin dashboard",
        "Assigned paths",
        "Completion reports"
      ],
      "seatMin": 5,
      "contactOnly": false
    },
    {
      "key": "enterprise",
      "name": "Enterprise",
      "book": "learn",
      "eurMonth": null,
      "eurYear": 15000,
      "inrMonth": null,
      "inrYear": 1200000,
      "generations": null,
      "blurb": "100+ seats, private library, your own generation quota.",
      "features": [
        "Everything in Team",
        "Private library",
        "Custom quota",
        "SCORM export rights",
        "DPA",
        "SLA"
      ],
      "seatMin": 100,
      "contactOnly": true
    }
  ],
  "create": [
    {
      "key": "create_free",
      "name": "Free",
      "book": "create",
      "eurMonth": 0,
      "eurYear": 0,
      "inrMonth": 0,
      "inrYear": 0,
      "generations": 3,
      "blurb": "Try it. Three reels a month, watermarked.",
      "features": [
        "3 generations/month",
        "Watermarked",
        "Public only"
      ],
      "seatMin": 1,
      "contactOnly": false
    },
    {
      "key": "creator",
      "name": "Creator",
      "book": "create",
      "eurMonth": 29,
      "eurYear": 290,
      "inrMonth": 1999,
      "inrYear": 19990,
      "generations": 150,
      "blurb": "For an educator building their own library.",
      "features": [
        "150 generations/month",
        "Publish into the library",
        "Revenue share",
        "No watermark"
      ],
      "seatMin": 1,
      "contactOnly": false
    },
    {
      "key": "studio",
      "name": "Studio",
      "book": "create",
      "eurMonth": 249,
      "eurYear": 2490,
      "inrMonth": 14999,
      "inrYear": 149990,
      "generations": 500,
      "blurb": "For a team producing course content.",
      "features": [
        "500 generations/month",
        "Brand kit",
        "Private library",
        "SCORM + LTI export of your own content",
        "Priority queue"
      ],
      "seatMin": 1,
      "contactOnly": false
    }
  ],
  "institutional": [
    {
      "key": "pilot",
      "name": "Semester pilot",
      "eur": 0,
      "inr": 0,
      "note": "One course, one semester, free. A sales instrument, permanently."
    },
    {
      "key": "programme",
      "name": "Programme licence",
      "eur": [
        6000,
        15000
      ],
      "inr": [
        300000,
        600000
      ],
      "note": "Unlimited students on one degree programme, per year."
    },
    {
      "key": "faculty",
      "name": "Faculty licence",
      "eur": [
        40000,
        null
      ],
      "inr": [
        3200000,
        null
      ],
      "note": "Whole faculty, per year."
    }
  ]
} as const;

export type PricingTier = (typeof PRICING)['learn'][number];
