// GENERATED by tools/gen_pricing.py from pipeline/pricing.py.
// Do not edit: run the generator instead. The three platforms
// drifted apart when this was hand-maintained.

export const PRICING = {
  "version": 1,
  "learn": [
    {
      "key": "free",
      "name": "Free",
      "book": "learn",
      "eurMonth": 0,
      "eurYear": 0,
      "inrMonth": 0,
      "inrYear": 0,
      "generations": 3,
      "blurb": "Unlimited watching, and three reels a month of your own.",
      "features": [
        "Unlimited watching",
        "Quiz tracking",
        "Concept map",
        "7 caption languages",
        "3 generations/month, watermarked"
      ],
      "seatMin": 1,
      "contactOnly": false
    },
    {
      "key": "learner",
      "name": "Learner",
      "book": "learn",
      "eurMonth": 4.99,
      "eurYear": 49.9,
      "inrMonth": 199,
      "inrYear": 1990,
      "generations": 30,
      "blurb": "For someone learning on their own time.",
      "features": [
        "Everything in Free",
        "Runnable notebooks",
        "Structured paths",
        "Certificates",
        "Offline downloads",
        "No ads",
        "30 generations/month"
      ],
      "seatMin": 1,
      "contactOnly": false
    },
    {
      "key": "creator",
      "name": "Creator",
      "book": "create",
      "eurMonth": 29.99,
      "eurYear": 299.9,
      "inrMonth": 999,
      "inrYear": 9990,
      "generations": 150,
      "blurb": "For an educator building their own library.",
      "features": [
        "Everything in Learner",
        "150 generations/month",
        "Publish into the library",
        "Revenue share",
        "No watermark",
        "SCORM + LTI export of your own content"
      ],
      "seatMin": 1,
      "contactOnly": false
    },
    {
      "key": "enterprise",
      "name": "Enterprise",
      "book": "learn",
      "eurMonth": 199,
      "eurYear": 1990,
      "inrMonth": null,
      "inrYear": null,
      "generations": null,
      "blurb": "Institutions and corporate L&D: courses built for your people.",
      "features": [
        "Everything in Creator",
        "Course-creation service",
        "Seats and cohorts",
        "SSO",
        "SCORM export",
        "LTI 1.3 launch",
        "Completion reports",
        "DPA",
        "SLA"
      ],
      "seatMin": 5,
      "contactOnly": true
    }
  ],
  "create": [],
  "institutional": [
    {
      "key": "pilot",
      "name": "Semester pilot",
      "eur": 0,
      "inr": 0,
      "note": "One course, one semester, free. A sales instrument, permanently."
    },
    {
      "key": "programme",
      "name": "Programme licence",
      "eur": [
        6000,
        15000
      ],
      "inr": [
        300000,
        600000
      ],
      "note": "Unlimited students on one degree programme, per year."
    },
    {
      "key": "faculty",
      "name": "Faculty licence",
      "eur": [
        40000,
        null
      ],
      "inr": [
        3200000,
        null
      ],
      "note": "Whole faculty, per year."
    }
  ]
} as const;

export type PricingTier = (typeof PRICING)['learn'][number];
